### ISSUE TITLE
Gmail and Facebook not loading

### ISSUE THREAD

**Issue by SeppNel** [gbaptista/luminous#6]
When I have this extension enabled, Facebook and Gmail will not load.
I tested with the "All Websites" option on and off and its always the same.

Here are some screnshoots of how it looks:

![facebook](https://user-images.githubusercontent.com/35899928/35486667-b68f74fe-0471-11e8-9c14-1429b99dad31.PNG)
![gmail](https://user-images.githubusercontent.com/35899928/35486668-b6c94d82-0471-11e8-9dcd-07b5c87b6475.PNG)

Im using:
- Windows 10
- Google Chrome (Version 64.0.3282.119)

**Comment by Atavic** [comment]
That's a feature!

**Comment by SeppNel** [comment]
But I want to see my emails...

**Comment by Atavic** [comment]
:+1: Legitimate opinion of yours, I was ironic. I humbly suggest to use at least two different browsers, see: https://gist.github.com/atcuno/3425484ac5cce5298932#browsing-strategies-

**Comment by gbaptista** [comment]
@SeppNel Thank you for reporting the issue!

I had this problem on other browsers too. I believe it is related to an mistake I made in manipulating the headers of _Content-Security-Policy_.

This problem was fixed in version 0.0.4:
 - https://github.com/gbaptista/luminous/pull/8/files#diff-190a095d8de73a8327a4e55afb2c7f9d

Can you please test again with version 0.0.4? Is already available in the [web store](https://chrome.google.com/webstore/detail/luminous-javascript-event/baacpbikplogpeecclpnajnlghmcldkb).

**Comment by gbaptista** [comment]
@Atavic This document (*HowTo: Privacy & Security Conscious Browsing*) It's amazing, thank you for sharing!

My humble two cents on this subject:

If someone likes *Google Chrome*, consider using [*Chromium*](https://chromium.org/)! It's exactly the same, without *Google's* modifications.

For those who are **really** concerned about privacy, it is worth thinking about alternative services like [Tutanota](https://tutanota.com) instead of *Gmail* and [Diaspora](https://diasporafoundation.org) instead of *Facebook*.

**Comment by SeppNel** [comment]
Yes its fixed in 0.0.4. Thank you for your awesome work.

@Atavic Like gbaptista said, nice info, I will take it in to consideration.

**Comment by Atavic** [comment]
:+1: at everyone. The doc has some flaws IMHO, as its VPN part. I'd like to link this one:
https://gist.github.com/kennwhite/1f3bc4d889b02b35d8aa
