### ISSUE TITLE
enable performance logging within the reports

### ISSUE THREAD

**Issue by jawz101** [gbaptista/luminous#64]
Aside from a privacy perspective (and I'm not a developer so this may not be relevant), I wonder if the extension could log performance data.  Say, we could load the Alexa top 1000 sites on Firefox for Android and see if certain popular scripts cause drastic performance bottlenecks - that might be good information for both webpage designers and browser developers to see how their code affects user experience.

Page load times might be another angle of this tool.  Like, as a developer, if I disable this random handle and notice a huge performance increase of my website, I may decide to code my webpage a little differently or remove a superfluous piece of code altogether.  Or a browser developer may be able to fix something in regards to that particular sort of coding style.

Does that make sense?  Maybe hopefully it gets the attention from a whole different developer community as well!

**Comment by gbaptista** [comment]
@jawz101 This is a wonderful idea! This type of blocking does not only affect page load but interactions with the site after loaded as well, since any executed codes continue to consume processing from your computer...

The problem of measuring code performance is that the act of measuring itself can be slower than the actually executed code. So we have a dangerous tradeoff on that.

I do not know how much information we can extract with WebExtensions API or JavaScript itself without affecting the browser performance. I'll do some experiments. Something that is relatively simple to do is try to calculate the execution time of each code.

An idea of what we could do: *[WIP] JavaScript Profiler Experiment #67*

And then we can include this information in the reports, as you said.

**Comment by jawz101** [comment]
It might be good to make it an optional setting so people who don't want to measure performance can use Luminous only for its blocking capabilities

**Comment by gbaptista** [comment]
@jawz101 Performance metrics available in version `0.0.22`. Thanks again for the suggestion and feel free to comment anything:

![4-popup-2](https://user-images.githubusercontent.com/29520/36647107-6cb84ff0-1a5f-11e8-9f8a-f6384f559b17.png)

![2-reports-1](https://user-images.githubusercontent.com/29520/36647111-80b0fbec-1a5f-11e8-83a9-6642f2b6ded0.png)

![5-reports-2](https://user-images.githubusercontent.com/29520/36647115-87739098-1a5f-11e8-9886-b2da460e7dcc.png)

**Comment by jawz101** [comment]
Awesome work!

**Comment by gbaptista** [comment]
Closing this issue for now. If new questions arise, feel free to open a new one. Thanks again!
